### PR TITLE
Populate read_replica_source when reading the replica

### PR DESCRIPTION
**Pull request by minkimipt**
When we getService on a read replica, we need to populate the read_replica_source to properly reflect that information in terraform state

closes https://github.com/timescale/Support-Dev-Collab/issues/2063

### CODE REVIEW

**Review by sebastianwebber — APPROVED** [review]
LGTM

**Comment by sebastianwebber** [comment]
Did some local tests and works as expected

```hcl
# setup ###########################
terraform {
  required_providers {
    timescale = {
      source  = "registry.terraform.io/providers/timescale"
      version = "~> 1.0"
    }
  }
}

provider "timescale" {
  project_id = var.ts_project_id
  access_key = var.ts_access_key
  secret_key = var.ts_secret_key
}

variable "ts_project_id" {
  type    = string
  default = "xo62e6nobm"
}

variable "ts_access_key" {
  type = string
}

variable "ts_secret_key" {
  type = string
}

# resources ################################
## main service
resource "timescale_service" "tf-test" {
  name                      = "tf-test"
  milli_cpu                 = 500
  memory_gb                 = 2
  region_code               = "us-west-2"
  connection_pooler_enabled = true
  enable_ha_replica         = true
  vpc_id                    = timescale_vpcs.vpc-diff-network.id
}

## imported read replica
resource "timescale_service" "replica-tf-test" {
  read_replica_source = timescale_service.tf-test.id
  name                = "replica-tf-test"
  milli_cpu           = 500
  memory_gb           = 2
  region_code         = "us-west-2"

  lifecycle {
    prevent_destroy = true
  }
}

resource "timescale_vpcs" "vpc-diff-network" {
  name        = "vpc-diff-network"
  cidr        = "192.168.0.0/24"
  region_code = "us-west-2"

  lifecycle {
    prevent_destroy = true
  }
}




# outputs ##################
## host connection info
output "host_addr" {
  value       = timescale_service.tf-test.hostname
  description = "Service Host Address"
}

output "host_port" {
  value       = timescale_service.tf-test.port
  description = "Service Host port"
}

## ha-replica connection info
output "replica_addr" {
  value       = timescale_service.tf-test.replica_hostname
  description = "Service Replica Host Address"
}

output "replica_port" {
  value       = timescale_service.tf-test.replica_port
  description = "Service Replica Host port"
}

## pooler connection info
output "pooler_addr" {
  value       = timescale_service.tf-test.pooler_hostname
  description = "Service Pooler Host Address"
}

output "pooler_port" {
  value       = timescale_service.tf-test.pooler_port
  description = "Service Pooler Host port"
}

## read replica endpoint
output "read_replica_addr" {
  value       = timescale_service.replica-tf-test.hostname
  description = "Service Replica Host Address"
}

output "read_replica_port" {
  value       = timescale_service.replica-tf-test.port
  description = "Service Replica Host port"
}
```

The import output:

```
❯ terraform import --var-file=secrets.tfvars 'timescale_service.replica-tf-test' qxem4ftdpj
timescale_service.replica-tf-test: Importing from ID "qxem4ftdpj"...
timescale_service.replica-tf-test: Import prepared!
  Prepared timescale_service for import
timescale_service.replica-tf-test: Refreshing state... [id=qxem4ftdpj]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

With the refresh we can see the outputs updated:

```shell
❯ terraform refresh --var-file=secrets.tfvars
timescale_vpcs.vpc-diff-network: Refreshing state... [name=vpc-diff-network]
timescale_service.tf-test: Refreshing state... [id=prd2y48ymp]
timescale_service.replica-tf-test: Refreshing state... [id=qxem4ftdpj]

Outputs:

host_addr = "prd2y48ymp.xo62e6nobm.vpc.tsdb.forge.timescale.com"
host_port = 5432
pooler_addr = "prd2y48ymp-pooler.xo62e6nobm.vpc.tsdb.forge.timescale.com"
pooler_port = 5432
read_replica_addr = "qxem4ftdpj.xo62e6nobm.tsdb.cloud.timescale.com"
read_replica_port = 31230
replica_addr = "prd2y48ymp-repl.xo62e6nobm.vpc.tsdb.forge.timescale.com"
replica_port = 5432
```

**Comment by sebastianwebber** [comment]
merging this pr to move forward with the dependabots

**Comment by sebastianwebber** [comment]
updating the integration tests timeout to 30min

**Comment by minkimipt** [comment]
Weird. First CI run worked in this branch and local tests work too. But now different tests fail in the CI with this crazy long stack traces.

**Pull request merged**
