### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sebastianwebber**
This PR updates the example file and adds more details about the development process.

It will updated and only merged after https://github.com/timescale/terraform-provider-timescale/pull/209

- [ ] add details about how to debug with Goland
- [ ] Do we need config for vscode?

### CODE REVIEW

**Comment by sebastianwebber** [comment]
it's easier to preview the changes by opening the file, like this
image

**Review by Khyme — APPROVED** [review]

**Comment by Khyme** [comment]
That is great 🤩

**Review by AldoFusterTurpin — APPROVED** [review]
Nice. Thanks!

**Comment by sebastianwebber** [comment]
# Debug config for Goland

## Runner config

```xml
<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="debug-local-build" type="GoApplicationRunConfiguration" factoryName="Go Application">
    <module name="terraform-provider-timescale" />
    <working_directory value="$PROJECT_DIR$" />
    <parameters value="--debug" />
    <kind value="DIRECTORY" />
    <package value="github.com/timescale/terraform-provider-timescale" />
    <directory value="$PROJECT_DIR$" />
    <filePath value="$PROJECT_DIR$/main.go" />
    <method v="2" />
  </configuration>
</component>
```

## Setup
> [!IMPORTANT]
> ensure that the `~/.terraformrc` contains:
>
> ```hcl
> provider_installation {
>  dev_overrides {
>      "registry.terraform.io/providers/timescale" = "$HOME/go/bin"
>  }
>
>   direct {}
> }
> ```

Start the debug, and get the binary path:

Screenshot 2024-09-03 at 22 31 49

Now ensure that the `~/go/bin/terraform-provider-timescale` points to the file that is running:

```shell
❯ ls -l ~/go/bin/terraform-provider-timescale
lrwxr-xr-x@ - seba  3 Sep 22:04 /Users/seba/go/bin/terraform-provider-timescale -> /Users/seba/Library/Caches/JetBrains/GoLand2024.1/tmp/GoLand/___go_build_main_go
```

## Running the debug

in the terminal export the env var `TF_REATTACH_PROVIDERS` then use terraform as usual. 

Example:

```shell
export TF_REATTACH_PROVIDERS='{"registry.terraform.io/providers/timescale":{"Protocol":"grpc","ProtocolVersion":6,"Pid":60212,"Test":true,"Addr":{"Network":"unix","String":"/var/folders/yx/7rrwmnvd3d14_qc362y5yt300000gn/T/plugin2566161580"}}}'

terraform plan
```

**Pull request merged**
